### PR TITLE
Feature/homepage aesthetics

### PR DESCRIPTION
**Pull request by KenneyC**
Summary: Added minimalistic aesthetics to the homepage. The colour scheme is based on 6 colours, and images are done in photoshop. Most changes are done in css, with some changes to the js files of each respective page.

Changes:
1. Added a solarnode logo, centered and styled with css. Image is inserted by adding a img tag in the TopNavigationBar.js file. 
2. Added a background image. Image is inserted into the HomePage.js file with a image tag. Styled in the HomePage.css file. 
3. Changed the background colour of both the top navigation bar and the homepage to match.
4. Added 2 sample links of both sides of the logo. Implemented by adding a <p> tag and styled, positioned with css.
5. Added a custom font for the links at the homepage. The font is located at the src folder.

Main changes : HomePage.js, Homepage.css, TopNavigationBar.js, TopNavigationBar.css

Known Issues:
1. Currently using a custom font which works on my build. But not working for @Edds390. 
Potential solution: The css uses url() to the find the font and it is currently set as "../../fonts/SFOrston.ttf". This link maybe different for other developers, hence the text is not using the desired font.
2. Hovering over the button used to change its colour but now it is not reactive. 
screen shot 2018-03-27 at 11 55 43 am

To do:
1. Integrate other pages to the links and the go button

Testing:
1. Just pull the changes, the visualisation should change. 
2. Check if there is a fonts folder inside the src folder.
3. Check If there is a icons folder inside the src folder.
4. Check if there is a solarnodeicon.png file and background.png file.

### CODE REVIEW

**Comment by Edds390** [comment]
Screenshot of font issue

image

**Comment by sejpat25** [comment]
The font display for the top navigation bar is the same as Edison's. I also noticed the background image is fairly zoomed in compared to the image displayed above. I have viewed it in Chrome & Edge and they are both the same. 
capture

**Comment by Edds390** [comment]
We'll merge it in for now since technically it's not breaking anything. We can come back and have a separate issue for making the background image resize as well as the fonts.

**Review by Edds390 — APPROVED** [review]

**Comment by SeoyoungC** [comment]
Also experiencing issue with font, and the solarnode logo is overlapping the coloured hexagon behind it:
screen shot 2018-03-27 at 1 31 06 pm

**Comment by KenneyC** [comment]
Major changes:
Image is now loaded from the Home.js file instead of directly accessed by the HomePage.css file. This allows more freedom in changing the characteristics of the image. 

Fixed:
Issue#17 : Background image now scales according to the window size. The image now does not maintain its original resolution so changing the scree size will stretch out the image size. 
screen shot 2018-03-27 at 4 33 09 pm
The image now maintains its position in the center no matter the resolution of the device.

Solution: Added some css into Home.css and 
Issue#3 : Solarnode and background image will now be separated. 
screen shot 2018-03-27 at 4 34 27 pm

Solution: Increased the height of the TopNavigationBar so the images don't overlap.
To be fixed:
Issue#1 Requesting the help of @elisalter so that the font can be imported into the product.

**Review by SeoyoungC — APPROVED** [review]
Looks good to me - we can open up a new issue for the font and handle that later!

**Pull request merged**
