### PR TITLE
Feature/value interface

### PR DESCRIPTION
**Pull request by Edds390**
Issue closes [25](https://github.com/Edds390/solarnetwork-aggregated-dashboard/issues/25).

____ 

### Features

- The value interface sidebar. The value represents the type of data that the user wishes to see from the graph. This can take the form of e.g. voltage, watt, current, etc. The sidebar is styled as a tab, with the selected value being highlighted to show the state which the graph is in.

_____
### Issues
- The value is hardcoded as a constant VALUE array inside DashboardPanel. This is to account for the fact that not all observations have the same list of values, so a unified list of expected values are coded in as an array. Our current solution assumes that the SolarNode API will return the same max number of value fields; if the API decides to add new value fields, our app won't be able to capture those.

### CODE REVIEW

**Comment by sejpat25** [comment]
There is currently a conflict with the DashboardPanel.js file - so firstly resolve these merge conflicts.
image
image


Good code implementation.  There were not many comments but the code itself was understandable without the need for them. One very minor fix is maintaining the convention of having the export default name the same as the related component js file name. So in this case, review ValueNavigationList.

**Comment by Edds390** [comment]
Fixed! Looks like the PR was outdated.

**Review by sejpat25 — APPROVED** [review]
Resolved the merge conflict & effectively implemented additional functionality (initial review was in a comment.

**Comment by SeoyoungC** [comment]
Value interface works great, but I noticed two small mostly visual issues:

1. Value label, where it seems to overlap the graph at times:
screen shot 2018-03-28 at 11 42 40 pm

2. Legend seems to be populated with all possible data sources despite there only being 3 on the actual graph:
screen shot 2018-03-28 at 11 45 38 pm
screen shot 2018-03-28 at 11 45 45 pm

However these are relatively minor issues, and the actual functionality of the value interface seems to work great!

**Comment by KenneyC** [comment]
@SeoyoungC I fixed the overlapping problem when I was improving aesthetics.
screen shot 2018-03-28 at 11 53 41 pm

**Review by KenneyC — APPROVED** [review]
Looks good to me 👍 No problems encountered and small bugs that can be fixed later, ignored for now.

**Comment by Edds390** [comment]
Issue raised for legend.

**Pull request merged**
